export const GETALLPOKEMONS = "GETALLPOKEMONS";
export const GETALLTYPES = "GETALLTYPES";
export const GETNEXTPAGE = "GETNEXTPAGE";
export const GETPREVIOUSPAGE = "GETPREVIOUSPAGE";
export const USERLOGIN = "USERLOGIN";
export const GETPOKEMONID = "GETPOKEMONID";
export const DELETEPOKEMONID = "DELETEPOKEMONID";
export const ERROR = "ERROR";
