### OBTENER TODOAS LAS POKEMONES
GET http://localhost:3001/pokemon

### OBTENER PROXIMA PAGINA
GET http://localhost:3001/pokemon/next

### OBTENER PAGINA ANTERIOR
GET http://localhost:3001/pokemon/previous

### OBTENER POKEMON POR ID o NAME
GET http://localhost:3001/pokemon/Aaron


### OBTENER LOS TIPOS DE LA API Y GUARDARLOS EN LA DB
GET http://localhost:3001/type

### CREAR UN NUEVO POKEMON
POST http://localhost:3001/pokemon
Content-Type: application/json

{
    "name": "Aaron",
    "types": [
      "rock",
      "fire"
    ],
    "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/1.svg",
    "hp": 150,
    "attack": 480,
    "defense": 123,
    "speed": 25,
    "height": 23,
    "weight": 45
}

### ACTUALIZAR UN POKEMON
PUT http://localhost:3001/pokemon/5746
Content-Type: application/json

{
  "name": "Pikachu",
  "types": ["water"],
  "weight": 1200
}

### ELIMINAR UN POKEMON
DELETE http://localhost:3001/pokemon/Aaron

### OBTENER USUARIO POR ID
GET http://localhost:3001/users/?email=martinjiro22@gmail.com&password=Pass123

### CREAR UN NUEVO USUARIO
POST http://localhost:3001/users
Content-Type: application/json

{
  "name": "Martin",
  "nameUser": "Martincito",
  "email": "martinjiro22@gmail.com",
  "password": "Pass123"

}


### BORRAR UN USUARIO
DELETE http://localhost:3001/users/1