### OBTENER TODOAS LAS POKEMONES
GET http://localhost:3001/pokemon

### OBTENER PROXIMA PAGINA
GET http://localhost:3001/pokemon/next

### OBTENER PAGINA ANTERIOR
GET http://localhost:3001/pokemon/previous

### OBTENER POKEMON POR ID o NAME
GET http://localhost:3001/pokemon/1

### FILTRAR POKEMONES POR SU TIPO
GET http://localhost:3001/type/fuego

### CREAR UN NUEVO POKEMON
POST http://localhost:3001/pokemon
Content-Type: application/json

{
    "nombre": "Aaron",
    "tipo": [
      "rock",
      "fire"
    ],
    "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/1.svg",
    "vida": 150,
    "ataque": 480,
    "defensa": 123,
    "altura": 23,
    "peso": 45
}

### ACTUALIZAR UN POKEMON
PUT http://localhost:3001/pokemon/5746
Content-Type: application/json

{
  "name": "Pikachu",
  "types": ["water"],
  "weight": 1200
}

### ELIMINAR UN POKEMON
DELETE http://localhost:3001/pokemon/Aaron

### OBTENER USUARIO POR ID
GET http://localhost:3001/users/2

### CREAR UN NUEVO USUARIO
POST http://localhost:3001/users
Content-Type: application/json

{
  "nombre": "Martin",
  "nombreUsuario": "Martincito",
  "email": "martinjiro22@gmail.com",
  "contraseña": "Pass123"

}

### MODIFICAR UN USUARIO
PUT http://localhost:3001/users/2
Content-Type: application/json

{
  "address": {
      "street": "Corval 555",
      "suite": "1°6",
      "city": "Buenos Aires",
      "zipcode": "14"
    },
  "email": "martinjiro22@gmail.com"
}

### BORRAR UN USUARIO
DELETE http://localhost:3001/users/40